# Generated by Django 5.0.2 on 2024-02-21 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
